import React from 'react';
import { motion } from 'framer-motion';
import { TrendingDown, ShieldCheck, DollarSign, Hammer } from 'lucide-react';

const coreBenefits = [
  {
    icon: TrendingDown,
    title: '95% Reduction in Change Orders',
    desc: 'Eliminate sudden field alterations by resolving dimensional errors inside design files instead of fabricating corrections under stress.'
  },
  {
    icon: ShieldCheck,
    title: 'Pre-Approved Asset Routing',
    desc: 'Provides contractors with coordinated pathways, ensuring structural trades secure layout prioritization based on code requirements.'
  },
  {
    icon: DollarSign,
    title: 'Protection of Material Margins',
    desc: 'Mitigate scrap waste generated by cutting into walls or scrapping off-size ducts due to unexpected structural interferences.'
  },
  {
    icon: Hammer,
    title: 'Seamless Pre-fabrication Support',
    desc: 'Enables components to be assembled offsite safely, confident that modules will match perfectly with field anchors.'
  }
];

export default function ClashSupport() {
  return (
    <section className="py-20 bg-white border-b border-slate-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
            How Clash Detection Protects Project Budgets
          </h2>
          <div className="h-1 w-16 bg-[#A43025] mx-auto mt-4 rounded-full" />
          <p className="mt-4 text-slate-600 text-lg">
            Shifting spatial verification from the physical field into the design office dramatically lowers schedule risk profiles.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {coreBenefits.map((benefit, index) => {
            const Icon = benefit.icon;
            return (
              <motion.div 
                key={index}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: index * 0.08 }}
                className="bg-white border border-slate-200 p-6 rounded-xl shadow-md relative group hover:border-[#A43025]/50 transition-colors"
              >
                <div className="w-12 h-12 rounded-lg bg-[#A43025]/5 border border-[#A43025]/10 text-[#A43025] flex items-center justify-center mb-5 group-hover:bg-[#A43025] group-hover:text-white transition-all">
                  <Icon className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-bold text-slate-900 mb-2">{benefit.title}</h3>
                <p className="text-sm text-slate-600 leading-relaxed">{benefit.desc}</p>
              </motion.div>
            );
          })}
        </div>

      </div>
    </section>
  );
}